dist: trusty

branches:
  only:
  - master

language: java

jdk: oraclejdk11

node_js:
  - "10"
script:
 - nvm install 10
 - cd frontend && npm install && npm test && npm run build
 - cd ../backend && mvn clean install
 