spring:
  datasource:
    hikari:
      allow-pool-suspension: true
      connection-timeout: 1000
    # set the database name. The connection string is auto-configured by spring-boot
    # ;DB_CLOSE_ON_EXIT=FALSE is part of the default config
    name: dev-h2-db

    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database: h2
    generate-ddl: false
    platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
    path: /h2
